/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CampaignVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAgreement"
      | "agreements"
      | "availableEscrow"
      | "campaignAdvertiser"
      | "campaignToken"
      | "campaigns"
      | "claim"
      | "claimable"
      | "createAgreement"
      | "createCampaign"
      | "fundCampaign"
      | "nextAgreementId"
      | "nextCampaignId"
      | "owner"
      | "recordSettlement"
      | "releaseReservedEscrow"
      | "renounceOwnership"
      | "reserveForSettlement"
      | "setAgreementActive"
      | "setCampaignActive"
      | "setSettlementContract"
      | "setSettlementOperator"
      | "settlementContract"
      | "settlementOperator"
      | "settlementRecorded"
      | "transferOwnership"
      | "withdrawUnreserved"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementAccepted"
      | "AgreementCreated"
      | "AgreementStatusChanged"
      | "CampaignCreated"
      | "CampaignFunded"
      | "CampaignStatusChanged"
      | "CampaignWithdrawal"
      | "Claimed"
      | "OwnershipTransferred"
      | "SettlementContractChanged"
      | "SettlementOperatorChanged"
      | "SettlementRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agreements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "availableEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignAdvertiser",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundCampaign",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextAgreementId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextCampaignId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordSettlement",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseReservedEscrow",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveForSettlement",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgreementActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlementOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlementRecorded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnreserved",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "availableEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignAdvertiser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextAgreementId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCampaignId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseReservedEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveForSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgreementActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnreserved",
    data: BytesLike
  ): Result;
}

export namespace AgreementAcceptedEvent {
  export type InputTuple = [agreementId: BigNumberish, publisher: AddressLike];
  export type OutputTuple = [agreementId: bigint, publisher: string];
  export interface OutputObject {
    agreementId: bigint;
    publisher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    campaignId: BigNumberish,
    publisher: AddressLike,
    allocationCap: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    campaignId: bigint,
    publisher: string,
    allocationCap: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    campaignId: bigint;
    publisher: string;
    allocationCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementStatusChangedEvent {
  export type InputTuple = [agreementId: BigNumberish, active: boolean];
  export type OutputTuple = [agreementId: bigint, active: boolean];
  export interface OutputObject {
    agreementId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    advertiser: AddressLike,
    token: AddressLike,
    initialFunding: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    advertiser: string,
    token: string,
    initialFunding: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    advertiser: string;
    token: string;
    initialFunding: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFundedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    amount: BigNumberish,
    totalFunded: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    amount: bigint,
    totalFunded: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    amount: bigint;
    totalFunded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignStatusChangedEvent {
  export type InputTuple = [campaignId: BigNumberish, active: boolean];
  export type OutputTuple = [campaignId: bigint, active: boolean];
  export interface OutputObject {
    campaignId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignWithdrawalEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    advertiser: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    advertiser: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    advertiser: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    publisher: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [publisher: string, token: string, amount: bigint];
  export interface OutputObject {
    publisher: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementContractChangedEvent {
  export type InputTuple = [
    previousContract: AddressLike,
    newContract: AddressLike
  ];
  export type OutputTuple = [previousContract: string, newContract: string];
  export interface OutputObject {
    previousContract: string;
    newContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementOperatorChangedEvent {
  export type InputTuple = [
    previousOperator: AddressLike,
    newOperator: AddressLike
  ];
  export type OutputTuple = [previousOperator: string, newOperator: string];
  export interface OutputObject {
    previousOperator: string;
    newOperator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementRecordedEvent {
  export type InputTuple = [
    settlementReference: BytesLike,
    agreementId: BigNumberish,
    amount: BigNumberish,
    evidenceRoot: BytesLike
  ];
  export type OutputTuple = [
    settlementReference: string,
    agreementId: bigint,
    amount: bigint,
    evidenceRoot: string
  ];
  export interface OutputObject {
    settlementReference: string;
    agreementId: bigint;
    amount: bigint;
    evidenceRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CampaignVault extends BaseContract {
  connect(runner?: ContractRunner | null): CampaignVault;
  waitForDeployment(): Promise<this>;

  interface: CampaignVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAgreement: TypedContractMethod<
    [agreementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  agreements: TypedContractMethod<
    [agreementId: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        campaignId: bigint;
        publisher: string;
        allocationCap: bigint;
        settled: bigint;
        accepted: boolean;
        active: boolean;
      }
    ],
    "view"
  >;

  availableEscrow: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  campaignAdvertiser: TypedContractMethod<
    [campaignId: BigNumberish],
    [string],
    "view"
  >;

  campaignToken: TypedContractMethod<
    [campaignId: BigNumberish],
    [string],
    "view"
  >;

  campaigns: TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        advertiser: string;
        token: string;
        funded: bigint;
        reserved: bigint;
        paid: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  claim: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  claimable: TypedContractMethod<
    [publisher: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  createAgreement: TypedContractMethod<
    [
      campaignId: BigNumberish,
      publisher: AddressLike,
      allocationCap: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [token: AddressLike, initialFunding: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  fundCampaign: TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextAgreementId: TypedContractMethod<[], [bigint], "view">;

  nextCampaignId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordSettlement: TypedContractMethod<
    [
      agreementId: BigNumberish,
      amount: BigNumberish,
      settlementReference: BytesLike,
      evidenceRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  releaseReservedEscrow: TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveForSettlement: TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAgreementActive: TypedContractMethod<
    [agreementId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  setCampaignActive: TypedContractMethod<
    [campaignId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  setSettlementContract: TypedContractMethod<
    [newSettlementContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setSettlementOperator: TypedContractMethod<
    [newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  settlementContract: TypedContractMethod<[], [string], "view">;

  settlementOperator: TypedContractMethod<[], [string], "view">;

  settlementRecorded: TypedContractMethod<
    [settlementReference: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawUnreserved: TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAgreement"
  ): TypedContractMethod<[agreementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agreements"
  ): TypedContractMethod<
    [agreementId: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        campaignId: bigint;
        publisher: string;
        allocationCap: bigint;
        settled: bigint;
        accepted: boolean;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "availableEscrow"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignAdvertiser"
  ): TypedContractMethod<[campaignId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "campaignToken"
  ): TypedContractMethod<[campaignId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        advertiser: string;
        token: string;
        funded: bigint;
        reserved: bigint;
        paid: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<
    [publisher: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      publisher: AddressLike,
      allocationCap: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [token: AddressLike, initialFunding: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextAgreementId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextCampaignId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordSettlement"
  ): TypedContractMethod<
    [
      agreementId: BigNumberish,
      amount: BigNumberish,
      settlementReference: BytesLike,
      evidenceRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseReservedEscrow"
  ): TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveForSettlement"
  ): TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgreementActive"
  ): TypedContractMethod<
    [agreementId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCampaignActive"
  ): TypedContractMethod<
    [campaignId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettlementContract"
  ): TypedContractMethod<
    [newSettlementContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettlementOperator"
  ): TypedContractMethod<[newOperator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settlementOperator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settlementRecorded"
  ): TypedContractMethod<[settlementReference: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUnreserved"
  ): TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgreementAccepted"
  ): TypedContractEvent<
    AgreementAcceptedEvent.InputTuple,
    AgreementAcceptedEvent.OutputTuple,
    AgreementAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementStatusChanged"
  ): TypedContractEvent<
    AgreementStatusChangedEvent.InputTuple,
    AgreementStatusChangedEvent.OutputTuple,
    AgreementStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFunded"
  ): TypedContractEvent<
    CampaignFundedEvent.InputTuple,
    CampaignFundedEvent.OutputTuple,
    CampaignFundedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignStatusChanged"
  ): TypedContractEvent<
    CampaignStatusChangedEvent.InputTuple,
    CampaignStatusChangedEvent.OutputTuple,
    CampaignStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignWithdrawal"
  ): TypedContractEvent<
    CampaignWithdrawalEvent.InputTuple,
    CampaignWithdrawalEvent.OutputTuple,
    CampaignWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlementContractChanged"
  ): TypedContractEvent<
    SettlementContractChangedEvent.InputTuple,
    SettlementContractChangedEvent.OutputTuple,
    SettlementContractChangedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementOperatorChanged"
  ): TypedContractEvent<
    SettlementOperatorChangedEvent.InputTuple,
    SettlementOperatorChangedEvent.OutputTuple,
    SettlementOperatorChangedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementRecorded"
  ): TypedContractEvent<
    SettlementRecordedEvent.InputTuple,
    SettlementRecordedEvent.OutputTuple,
    SettlementRecordedEvent.OutputObject
  >;

  filters: {
    "AgreementAccepted(uint256,address)": TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;
    AgreementAccepted: TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;

    "AgreementCreated(uint256,uint256,address,uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementStatusChanged(uint256,bool)": TypedContractEvent<
      AgreementStatusChangedEvent.InputTuple,
      AgreementStatusChangedEvent.OutputTuple,
      AgreementStatusChangedEvent.OutputObject
    >;
    AgreementStatusChanged: TypedContractEvent<
      AgreementStatusChangedEvent.InputTuple,
      AgreementStatusChangedEvent.OutputTuple,
      AgreementStatusChangedEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,address,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignFunded(uint256,uint256,uint256)": TypedContractEvent<
      CampaignFundedEvent.InputTuple,
      CampaignFundedEvent.OutputTuple,
      CampaignFundedEvent.OutputObject
    >;
    CampaignFunded: TypedContractEvent<
      CampaignFundedEvent.InputTuple,
      CampaignFundedEvent.OutputTuple,
      CampaignFundedEvent.OutputObject
    >;

    "CampaignStatusChanged(uint256,bool)": TypedContractEvent<
      CampaignStatusChangedEvent.InputTuple,
      CampaignStatusChangedEvent.OutputTuple,
      CampaignStatusChangedEvent.OutputObject
    >;
    CampaignStatusChanged: TypedContractEvent<
      CampaignStatusChangedEvent.InputTuple,
      CampaignStatusChangedEvent.OutputTuple,
      CampaignStatusChangedEvent.OutputObject
    >;

    "CampaignWithdrawal(uint256,address,uint256)": TypedContractEvent<
      CampaignWithdrawalEvent.InputTuple,
      CampaignWithdrawalEvent.OutputTuple,
      CampaignWithdrawalEvent.OutputObject
    >;
    CampaignWithdrawal: TypedContractEvent<
      CampaignWithdrawalEvent.InputTuple,
      CampaignWithdrawalEvent.OutputTuple,
      CampaignWithdrawalEvent.OutputObject
    >;

    "Claimed(address,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlementContractChanged(address,address)": TypedContractEvent<
      SettlementContractChangedEvent.InputTuple,
      SettlementContractChangedEvent.OutputTuple,
      SettlementContractChangedEvent.OutputObject
    >;
    SettlementContractChanged: TypedContractEvent<
      SettlementContractChangedEvent.InputTuple,
      SettlementContractChangedEvent.OutputTuple,
      SettlementContractChangedEvent.OutputObject
    >;

    "SettlementOperatorChanged(address,address)": TypedContractEvent<
      SettlementOperatorChangedEvent.InputTuple,
      SettlementOperatorChangedEvent.OutputTuple,
      SettlementOperatorChangedEvent.OutputObject
    >;
    SettlementOperatorChanged: TypedContractEvent<
      SettlementOperatorChangedEvent.InputTuple,
      SettlementOperatorChangedEvent.OutputTuple,
      SettlementOperatorChangedEvent.OutputObject
    >;

    "SettlementRecorded(bytes32,uint256,uint256,bytes32)": TypedContractEvent<
      SettlementRecordedEvent.InputTuple,
      SettlementRecordedEvent.OutputTuple,
      SettlementRecordedEvent.OutputObject
    >;
    SettlementRecorded: TypedContractEvent<
      SettlementRecordedEvent.InputTuple,
      SettlementRecordedEvent.OutputTuple,
      SettlementRecordedEvent.OutputObject
    >;
  };
}
