/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AdFlowSettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAgreement"
      | "agreements"
      | "claim"
      | "claimable"
      | "createAgreement"
      | "nextAgreementId"
      | "owner"
      | "renounceOwnership"
      | "setAgreementActive"
      | "setSettlementOperator"
      | "settleEpoch"
      | "settledEpochs"
      | "settlementOperator"
      | "transferOwnership"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementAccepted"
      | "AgreementCreated"
      | "AgreementPaused"
      | "Claimed"
      | "EpochSettled"
      | "OwnershipTransferred"
      | "SettlementOperatorChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agreements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nextAgreementId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgreementActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleEpoch",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settledEpochs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acceptAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextAgreementId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgreementActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settledEpochs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace AgreementAcceptedEvent {
  export type InputTuple = [agreementId: BigNumberish, publisher: AddressLike];
  export type OutputTuple = [agreementId: bigint, publisher: string];
  export interface OutputObject {
    agreementId: bigint;
    publisher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    campaignId: BigNumberish,
    publisher: AddressLike,
    rateAtomic: BigNumberish,
    unitScale: BigNumberish,
    allocationCapAtomic: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    campaignId: bigint,
    publisher: string,
    rateAtomic: bigint,
    unitScale: bigint,
    allocationCapAtomic: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    campaignId: bigint;
    publisher: string;
    rateAtomic: bigint;
    unitScale: bigint;
    allocationCapAtomic: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementPausedEvent {
  export type InputTuple = [agreementId: BigNumberish, active: boolean];
  export type OutputTuple = [agreementId: bigint, active: boolean];
  export interface OutputObject {
    agreementId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    publisher: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [publisher: string, token: string, amount: bigint];
  export interface OutputObject {
    publisher: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpochSettledEvent {
  export type InputTuple = [
    epochReference: BytesLike,
    agreementId: BigNumberish,
    verifiedUnits: BigNumberish,
    payoutAtomic: BigNumberish,
    evidenceRoot: BytesLike
  ];
  export type OutputTuple = [
    epochReference: string,
    agreementId: bigint,
    verifiedUnits: bigint,
    payoutAtomic: bigint,
    evidenceRoot: string
  ];
  export interface OutputObject {
    epochReference: string;
    agreementId: bigint;
    verifiedUnits: bigint;
    payoutAtomic: bigint;
    evidenceRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementOperatorChangedEvent {
  export type InputTuple = [
    previousOperator: AddressLike,
    newOperator: AddressLike
  ];
  export type OutputTuple = [previousOperator: string, newOperator: string];
  export interface OutputObject {
    previousOperator: string;
    newOperator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AdFlowSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): AdFlowSettlement;
  waitForDeployment(): Promise<this>;

  interface: AdFlowSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAgreement: TypedContractMethod<
    [agreementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  agreements: TypedContractMethod<
    [agreementId: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        campaignId: bigint;
        publisher: string;
        rateAtomic: bigint;
        unitScale: bigint;
        allocationCapAtomic: bigint;
        settledAtomic: bigint;
        accepted: boolean;
        active: boolean;
      }
    ],
    "view"
  >;

  claim: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  claimable: TypedContractMethod<
    [publisher: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  createAgreement: TypedContractMethod<
    [
      campaignId: BigNumberish,
      publisher: AddressLike,
      rateAtomic: BigNumberish,
      unitScale: BigNumberish,
      allocationCapAtomic: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  nextAgreementId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgreementActive: TypedContractMethod<
    [agreementId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  setSettlementOperator: TypedContractMethod<
    [newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  settleEpoch: TypedContractMethod<
    [
      agreementId: BigNumberish,
      verifiedUnits: BigNumberish,
      epochReference: BytesLike,
      evidenceRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  settledEpochs: TypedContractMethod<
    [epochReference: BytesLike],
    [boolean],
    "view"
  >;

  settlementOperator: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAgreement"
  ): TypedContractMethod<[agreementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agreements"
  ): TypedContractMethod<
    [agreementId: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        campaignId: bigint;
        publisher: string;
        rateAtomic: bigint;
        unitScale: bigint;
        allocationCapAtomic: bigint;
        settledAtomic: bigint;
        accepted: boolean;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<
    [publisher: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      publisher: AddressLike,
      rateAtomic: BigNumberish,
      unitScale: BigNumberish,
      allocationCapAtomic: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextAgreementId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgreementActive"
  ): TypedContractMethod<
    [agreementId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettlementOperator"
  ): TypedContractMethod<[newOperator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleEpoch"
  ): TypedContractMethod<
    [
      agreementId: BigNumberish,
      verifiedUnits: BigNumberish,
      epochReference: BytesLike,
      evidenceRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settledEpochs"
  ): TypedContractMethod<[epochReference: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "settlementOperator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgreementAccepted"
  ): TypedContractEvent<
    AgreementAcceptedEvent.InputTuple,
    AgreementAcceptedEvent.OutputTuple,
    AgreementAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementPaused"
  ): TypedContractEvent<
    AgreementPausedEvent.InputTuple,
    AgreementPausedEvent.OutputTuple,
    AgreementPausedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "EpochSettled"
  ): TypedContractEvent<
    EpochSettledEvent.InputTuple,
    EpochSettledEvent.OutputTuple,
    EpochSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlementOperatorChanged"
  ): TypedContractEvent<
    SettlementOperatorChangedEvent.InputTuple,
    SettlementOperatorChangedEvent.OutputTuple,
    SettlementOperatorChangedEvent.OutputObject
  >;

  filters: {
    "AgreementAccepted(uint256,address)": TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;
    AgreementAccepted: TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;

    "AgreementCreated(uint256,uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementPaused(uint256,bool)": TypedContractEvent<
      AgreementPausedEvent.InputTuple,
      AgreementPausedEvent.OutputTuple,
      AgreementPausedEvent.OutputObject
    >;
    AgreementPaused: TypedContractEvent<
      AgreementPausedEvent.InputTuple,
      AgreementPausedEvent.OutputTuple,
      AgreementPausedEvent.OutputObject
    >;

    "Claimed(address,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "EpochSettled(bytes32,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      EpochSettledEvent.InputTuple,
      EpochSettledEvent.OutputTuple,
      EpochSettledEvent.OutputObject
    >;
    EpochSettled: TypedContractEvent<
      EpochSettledEvent.InputTuple,
      EpochSettledEvent.OutputTuple,
      EpochSettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlementOperatorChanged(address,address)": TypedContractEvent<
      SettlementOperatorChangedEvent.InputTuple,
      SettlementOperatorChangedEvent.OutputTuple,
      SettlementOperatorChangedEvent.OutputObject
    >;
    SettlementOperatorChanged: TypedContractEvent<
      SettlementOperatorChangedEvent.InputTuple,
      SettlementOperatorChangedEvent.OutputTuple,
      SettlementOperatorChangedEvent.OutputObject
    >;
  };
}
