/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICampaignVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "campaignAdvertiser"
      | "campaignToken"
      | "releaseReservedEscrow"
      | "reserveForSettlement"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "campaignAdvertiser",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseReservedEscrow",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveForSettlement",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "campaignAdvertiser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseReservedEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveForSettlement",
    data: BytesLike
  ): Result;
}

export interface ICampaignVault extends BaseContract {
  connect(runner?: ContractRunner | null): ICampaignVault;
  waitForDeployment(): Promise<this>;

  interface: ICampaignVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  campaignAdvertiser: TypedContractMethod<
    [campaignId: BigNumberish],
    [string],
    "view"
  >;

  campaignToken: TypedContractMethod<
    [campaignId: BigNumberish],
    [string],
    "view"
  >;

  releaseReservedEscrow: TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  reserveForSettlement: TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "campaignAdvertiser"
  ): TypedContractMethod<[campaignId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "campaignToken"
  ): TypedContractMethod<[campaignId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "releaseReservedEscrow"
  ): TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveForSettlement"
  ): TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
