/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICampaignVault,
  ICampaignVaultInterface,
} from "../../../contracts/AdFlowSettlement.sol/ICampaignVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
    ],
    name: "campaignAdvertiser",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
    ],
    name: "campaignToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "releaseReservedEscrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "reserveForSettlement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICampaignVault__factory {
  static readonly abi = _abi;
  static createInterface(): ICampaignVaultInterface {
    return new Interface(_abi) as ICampaignVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICampaignVault {
    return new Contract(address, _abi, runner) as unknown as ICampaignVault;
  }
}
